/**
 * OpenQuestion type definitions.
 * Matches the schema in spec/openQuestionPolicy.md and spec/projectSpec.md
 */

// =============================================================================
// Enums
// =============================================================================

/**
 * Severity levels for OpenQuestions.
 * - BLOCKING: Must resolve before commit; prevents forward progress
 * - IMPORTANT: Surfaced prominently; should resolve before phase transition
 * - SOFT: Background suggestion; may remain unresolved
 */
export type OQSeverity = 'BLOCKING' | 'IMPORTANT' | 'SOFT';

/**
 * Phases when OpenQuestions are typically surfaced.
 * - OUTLINE: Beat structure and scene placement
 * - DRAFT: Scene content, characters, locations fleshed out
 * - REVISION: Polish, thematic grounding, arc completion
 */
export type OQPhase = 'OUTLINE' | 'DRAFT' | 'REVISION';

/**
 * Domains that OpenQuestions belong to.
 */
export type OQDomain =
  | 'STRUCTURE'
  | 'SCENE'
  | 'CHARACTER'
  | 'CONFLICT'
  | 'THEME_MOTIF';

/**
 * All OpenQuestion types.
 *
 * STRUCTURE domain:
 * - BeatUnrealized: Beat exists with 0 Scenes fulfilling it
 * - ActImbalance: Total scenes in an act == 0 while neighboring acts have ≥ 2
 * - SceneUnplaced: Scene exists with missing/invalid beat assignment
 *
 * SCENE domain:
 * - SceneNeedsOverview: Scene.scene_overview missing or < 20 chars
 * - SceneHasNoCast: Scene has 0 HAS_CHARACTER edges
 * - SceneNeedsLocation: Scene has 0 LOCATED_AT edges
 *
 * CHARACTER domain:
 * - CharacterUnderspecified: Character has no description and appears in ≥ 2 scenes
 * - MissingCharacterArc: Character appears in ≥ 3 scenes and has no HAS_ARC edge
 * - ArcUngrounded: CharacterArc exists with 0 turn_refs
 *
 * CONFLICT domain:
 * - ConflictNeedsParties: Conflict exists with 0 INVOLVES edges
 * - ConflictNeedsManifestation: Conflict exists with 0 MANIFESTS_IN edges
 *
 * THEME_MOTIF domain:
 * - ThemeUngrounded: Theme has status FLOATING and 0 EXPRESSED_IN edges
 * - MotifUngrounded: Motif has status FLOATING and 0 APPEARS_IN edges
 */
export type OQType =
  // Structure domain
  | 'BeatUnrealized'
  | 'ActImbalance'
  | 'SceneUnplaced'
  // Scene domain
  | 'SceneNeedsOverview'
  | 'SceneHasNoCast'
  | 'SceneNeedsLocation'
  // Character domain
  | 'CharacterUnderspecified'
  | 'MissingCharacterArc'
  | 'ArcUngrounded'
  // Conflict domain
  | 'ConflictNeedsParties'
  | 'ConflictNeedsManifestation'
  // Theme/Motif domain
  | 'ThemeUngrounded'
  | 'MotifUngrounded';

// =============================================================================
// OpenQuestion Interface
// =============================================================================

/**
 * OpenQuestion represents a deterministically derived gap in the knowledge graph.
 * These are generated by schema rules and signal areas of opportunity.
 */
export interface OpenQuestion {
  id: string;
  type: OQType;
  domain: OQDomain;
  severity: OQSeverity;
  phase: OQPhase;
  group_key: string;
  target_node_id?: string;
  message: string;
}

// =============================================================================
// OpenQuestion Metadata
// =============================================================================

/**
 * Metadata about each OpenQuestion type.
 */
export interface OQTypeInfo {
  type: OQType;
  domain: OQDomain;
  defaultSeverity: OQSeverity;
  phase: OQPhase;
  description: string;
}

/**
 * Metadata for all OpenQuestion types.
 */
export const OQ_TYPE_INFO: Record<OQType, OQTypeInfo> = {
  // STRUCTURE domain
  BeatUnrealized: {
    type: 'BeatUnrealized',
    domain: 'STRUCTURE',
    defaultSeverity: 'IMPORTANT',
    phase: 'OUTLINE',
    description: 'Beat exists with 0 Scenes fulfilling it',
  },
  ActImbalance: {
    type: 'ActImbalance',
    domain: 'STRUCTURE',
    defaultSeverity: 'IMPORTANT',
    phase: 'OUTLINE',
    description: 'Act has no scenes while neighboring acts have content',
  },
  SceneUnplaced: {
    type: 'SceneUnplaced',
    domain: 'STRUCTURE',
    defaultSeverity: 'BLOCKING',
    phase: 'OUTLINE',
    description: 'Scene exists with missing/invalid beat assignment',
  },

  // SCENE domain
  SceneNeedsOverview: {
    type: 'SceneNeedsOverview',
    domain: 'SCENE',
    defaultSeverity: 'BLOCKING',
    phase: 'DRAFT',
    description: 'Scene.scene_overview missing or < 20 chars',
  },
  SceneHasNoCast: {
    type: 'SceneHasNoCast',
    domain: 'SCENE',
    defaultSeverity: 'IMPORTANT',
    phase: 'DRAFT',
    description: 'Scene has 0 HAS_CHARACTER edges',
  },
  SceneNeedsLocation: {
    type: 'SceneNeedsLocation',
    domain: 'SCENE',
    defaultSeverity: 'IMPORTANT',
    phase: 'DRAFT',
    description: 'Scene has 0 LOCATED_AT edges',
  },

  // CHARACTER domain
  CharacterUnderspecified: {
    type: 'CharacterUnderspecified',
    domain: 'CHARACTER',
    defaultSeverity: 'SOFT',
    phase: 'OUTLINE',
    description: 'Character has no description and appears in ≥ 2 scenes',
  },
  MissingCharacterArc: {
    type: 'MissingCharacterArc',
    domain: 'CHARACTER',
    defaultSeverity: 'IMPORTANT',
    phase: 'DRAFT',
    description: 'Character appears in ≥ 3 scenes and has no HAS_ARC edge',
  },
  ArcUngrounded: {
    type: 'ArcUngrounded',
    domain: 'CHARACTER',
    defaultSeverity: 'SOFT',
    phase: 'REVISION',
    description: 'CharacterArc exists with 0 turn_refs',
  },

  // CONFLICT domain
  ConflictNeedsParties: {
    type: 'ConflictNeedsParties',
    domain: 'CONFLICT',
    defaultSeverity: 'IMPORTANT',
    phase: 'DRAFT',
    description: 'Conflict exists with 0 INVOLVES edges',
  },
  ConflictNeedsManifestation: {
    type: 'ConflictNeedsManifestation',
    domain: 'CONFLICT',
    defaultSeverity: 'IMPORTANT',
    phase: 'DRAFT',
    description: "Conflict exists with 0 MANIFESTS_IN edges",
  },

  // THEME_MOTIF domain
  ThemeUngrounded: {
    type: 'ThemeUngrounded',
    domain: 'THEME_MOTIF',
    defaultSeverity: 'SOFT',
    phase: 'REVISION',
    description: 'Theme has status FLOATING and 0 EXPRESSED_IN edges',
  },
  MotifUngrounded: {
    type: 'MotifUngrounded',
    domain: 'THEME_MOTIF',
    defaultSeverity: 'SOFT',
    phase: 'REVISION',
    description: "Motif has status FLOATING and 0 APPEARS_IN edges",
  },
};

// =============================================================================
// Lists for Validation
// =============================================================================

export const OQ_TYPES: OQType[] = [
  'BeatUnrealized',
  'ActImbalance',
  'SceneUnplaced',
  'SceneNeedsOverview',
  'SceneHasNoCast',
  'SceneNeedsLocation',
  'CharacterUnderspecified',
  'MissingCharacterArc',
  'ArcUngrounded',
  'ConflictNeedsParties',
  'ConflictNeedsManifestation',
  'ThemeUngrounded',
  'MotifUngrounded',
];

export const OQ_DOMAINS: OQDomain[] = [
  'STRUCTURE',
  'SCENE',
  'CHARACTER',
  'CONFLICT',
  'THEME_MOTIF',
];

export const OQ_PHASES: OQPhase[] = ['OUTLINE', 'DRAFT', 'REVISION'];

export const OQ_SEVERITIES: OQSeverity[] = ['BLOCKING', 'IMPORTANT', 'SOFT'];

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Check if an OQ type is valid.
 */
export function isValidOQType(type: string): type is OQType {
  return OQ_TYPES.includes(type as OQType);
}

/**
 * Get metadata for an OQ type.
 */
export function getOQTypeInfo(type: OQType): OQTypeInfo {
  return OQ_TYPE_INFO[type];
}

/**
 * Get OQ types for a specific domain.
 */
export function getOQTypesForDomain(domain: OQDomain): OQType[] {
  return OQ_TYPES.filter((type) => OQ_TYPE_INFO[type].domain === domain);
}

/**
 * Get OQ types for a specific phase.
 */
export function getOQTypesForPhase(phase: OQPhase): OQType[] {
  return OQ_TYPES.filter((type) => OQ_TYPE_INFO[type].phase === phase);
}
