/**
 * OpenQuestion type definitions.
 * Matches the schema in spec/openQuestionPolicy.md and spec/projectSpec.md
 */

// =============================================================================
// Enums
// =============================================================================

/**
 * Domains that OpenQuestions belong to.
 */
export type OQDomain =
  | 'STRUCTURE'
  | 'SCENE'
  | 'CHARACTER';

/**
 * All OpenQuestion types.
 *
 * STRUCTURE domain:
 * - BeatUnrealized: Beat exists with 0 Scenes fulfilling it
 * - ActImbalance: Total scenes in an act == 0 while neighboring acts have ≥ 2
 * - SceneUnplaced: Scene exists with missing/invalid beat assignment
 *
 * SCENE domain:
 * - SceneNeedsOverview: Scene.scene_overview missing or < 20 chars
 * - SceneHasNoCast: Scene has 0 HAS_CHARACTER edges
 * - SceneNeedsLocation: Scene has 0 LOCATED_AT edges
 *
 * CHARACTER domain:
 * - CharacterUnderspecified: Character has no description and appears in ≥ 2 scenes
 * - MissingCharacterArc: Character appears in ≥ 3 scenes and has no HAS_ARC edge
 * - ArcUngrounded: CharacterArc exists with 0 turn_refs
 */
export type OQType =
  // Structure domain
  | 'BeatUnrealized'
  | 'ActImbalance'
  | 'SceneUnplaced'
  // Scene domain
  | 'SceneNeedsOverview'
  | 'SceneHasNoCast'
  | 'SceneNeedsLocation'
  // Character domain
  | 'CharacterUnderspecified'
  | 'MissingCharacterArc'
  | 'ArcUngrounded';

// =============================================================================
// OpenQuestion Interface
// =============================================================================

/**
 * OpenQuestion represents a deterministically derived gap in the knowledge graph.
 * These are generated by schema rules and signal areas of opportunity.
 */
export interface OpenQuestion {
  id: string;
  type: OQType;
  domain: OQDomain;
  group_key: string;
  target_node_id?: string;
  message: string;
}

// =============================================================================
// OpenQuestion Metadata
// =============================================================================

/**
 * Metadata about each OpenQuestion type.
 */
export interface OQTypeInfo {
  type: OQType;
  domain: OQDomain;
  description: string;
}

/**
 * Metadata for all OpenQuestion types.
 */
export const OQ_TYPE_INFO: Record<OQType, OQTypeInfo> = {
  // STRUCTURE domain
  BeatUnrealized: {
    type: 'BeatUnrealized',
    domain: 'STRUCTURE',
    description: 'Beat exists with 0 Scenes fulfilling it',
  },
  ActImbalance: {
    type: 'ActImbalance',
    domain: 'STRUCTURE',
    description: 'Act has no scenes while neighboring acts have content',
  },
  SceneUnplaced: {
    type: 'SceneUnplaced',
    domain: 'STRUCTURE',
    description: 'Scene exists with missing/invalid beat assignment',
  },

  // SCENE domain
  SceneNeedsOverview: {
    type: 'SceneNeedsOverview',
    domain: 'SCENE',
    description: 'Scene.scene_overview missing or < 20 chars',
  },
  SceneHasNoCast: {
    type: 'SceneHasNoCast',
    domain: 'SCENE',
    description: 'Scene has 0 HAS_CHARACTER edges',
  },
  SceneNeedsLocation: {
    type: 'SceneNeedsLocation',
    domain: 'SCENE',
    description: 'Scene has 0 LOCATED_AT edges',
  },

  // CHARACTER domain
  CharacterUnderspecified: {
    type: 'CharacterUnderspecified',
    domain: 'CHARACTER',
    description: 'Character has no description and appears in ≥ 2 scenes',
  },
  MissingCharacterArc: {
    type: 'MissingCharacterArc',
    domain: 'CHARACTER',
    description: 'Character appears in ≥ 3 scenes and has no HAS_ARC edge',
  },
  ArcUngrounded: {
    type: 'ArcUngrounded',
    domain: 'CHARACTER',
    description: 'CharacterArc exists with 0 turn_refs',
  },
};

// =============================================================================
// Lists for Validation
// =============================================================================

export const OQ_TYPES: OQType[] = [
  'BeatUnrealized',
  'ActImbalance',
  'SceneUnplaced',
  'SceneNeedsOverview',
  'SceneHasNoCast',
  'SceneNeedsLocation',
  'CharacterUnderspecified',
  'MissingCharacterArc',
  'ArcUngrounded',
];

export const OQ_DOMAINS: OQDomain[] = [
  'STRUCTURE',
  'SCENE',
  'CHARACTER',
];

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Check if an OQ type is valid.
 */
export function isValidOQType(type: string): type is OQType {
  return OQ_TYPES.includes(type as OQType);
}

/**
 * Get metadata for an OQ type.
 */
export function getOQTypeInfo(type: OQType): OQTypeInfo {
  return OQ_TYPE_INFO[type];
}

/**
 * Get OQ types for a specific domain.
 */
export function getOQTypesForDomain(domain: OQDomain): OQType[] {
  return OQ_TYPES.filter((type) => OQ_TYPE_INFO[type].domain === domain);
}
